name: Deploy Medusa Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.9.5" 
      - name: Initialize Terraform
        run: terraform init
      - name: Apply Terraform changes
        run: terraform apply -auto-approve
