

# .github/workflows/deploy.yml

name: Medusa CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to AWS
        uses: aws-actions/login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
      - name: Build and push Medusa image
        run: |
          docker build -t medusajs/medusa:latest .
          docker push medusajs/medusa:latest
      - name: Update ECS task definition
        run: |
          aws ecs update-task-definition --cluster medusa-ecs-cluster --task-definition medusa-task-definition --container-definitions file://container-definitions.json
      - name: Update ECS service
        run: |
          aws ecs update-service --cluster medusa-ecs-cluster --service medusa-service --task-definition medusa-task-definition

